### ISSUE TITLE
Clean ups?

### ISSUE THREAD

**Issue by confact** [cable-cr/cable#19]
@fernandes how do you feel about doing some clean-ups in the code? @jgaskins have done a lot of simplifications in his fork https://github.com/jgaskins/cable we could use.

Examples:
- using `Cable::Handler(ApplicationCable::Connection).new`, instead of `Cable::Handler.new(ApplicationCable::Connection)`
- using `property` and `getter` in macros instead of writing up all the methods.
- using mutex for subscribing, unsubscribe, and those important parts.

I would like @jgaskins to get the credits on those changes if they are done. He is the one that has does fixes already in his fork :)

**Comment by fernandes** [comment]
Absolutely, I see no reason why not, as this is going to be better for everyone.. I'm totally in

I'm just not sure if @jgaskins wants to keep his fork or open the PRs, thoughts? 😄

**Comment by jgaskins** [comment]
@confact Thanks for the shout out! 🙂

@fernandes Definitely, my changes came out of integrating this shard with [my implementation of Basecamp's Turbo](https://github.com/jgaskins/turbo) in Crystal for streaming UI updates without writing JS. I'm adding some of that functionality to an existing app and it uncovered a few spots in this shard that were difficult to integrate with. Missing unsubscribe was one of the major ones — it caused a memory leak and sometimes multiple WebSocket updates because subscriptions were never being removed.

I've been using my fork mainly so I could iterate quickly and be messy with it. 😂 Getting those in as PRs here should mostly be simple — cherry-picking [the commits](https://github.com/cable-cr/cable/compare/master...jgaskins:master) into their own branches and then figuring out how to wrap tests around ones that add functionality or change existing, because I very much did not write or update any automated tests yet.

**Comment by fernandes** [comment]
awesome! thanks for hopping in @jgaskins ! I'm super excited and can wait for this turbo implementation, if you need some help, just let us know 😄 

this week things I'm almost without hours to dedicate to OS, next week I'll prioritize to tackle these cleanups... cheers!
