### ISSUE TITLE
Allowing for no token

### ISSUE THREAD

**Issue by jwoertink** [cable-cr/cable#6]
When you generate a new rails app, the default `consumer.js` created doesn't specify any query params, and it builds out the websocket URL for you. https://github.com/rails/rails/blob/master/actioncable/lib/rails/generators/channel/templates/javascript/consumer.js.tt

```javascript
import { createConsumer } from "@rails/actioncable"

export default createConsumer()
```

But if we do this, we get the error `Unhandled exception in spawn: Not token on params (Exception)`. Would there be a way to allow for no token at all? Or is it best practice to always include this?

**Comment by fernandes** [comment]
Using `cable` standalone, the only way to authenticate an user is using a JWT token on the URL, the good part, you can authenticate with just a JWT, the bad, a token on the URL is no good once it can be sniffed even when using HTTPS

When using with a framework as Lucky, the AC JS client sends the cookie, so we can get the auth information from the (encrypted) cookie... that's the best scenario for sure

once we integrate `cable` with some framework, then yes, we'll need to allow no token

**Comment by jgaskins** [comment]
I just ran into this problem myself while working on a Crystal port of some of the other Rails Hotwire components.

Making authenticated connections a first-class citizen is awesome, but not all apps use authentication for WebSockets. For example, [Pusher](https://pusher.com) connections aren't authenticated unless the client app [subscribes to a private channel](https://pusher.com/docs/channels/using_channels/private-channels). Since it's not universally applicable it may make sense to let the application determine how (or whether) to authenticate the connection.

> a token on the URL is no good once it can be sniffed even when using HTTPS

Can you expand on this a bit? The only way I can imagine being able to sniff it is if the request line were sent in plaintext.

**Comment by jwoertink** [comment]
What we ended up doing in our app is

```javascript
import { createConsumer } from "@rails/actioncable";

const wsEndpoint = process.env.MIX_WS_ENDPOINT;

export default createConsumer(wsEndpoint);
```

I think rails just sets this value from a meta tag in the application layout. And then the value of `token` is just `"jwt"`. We're handling the auth through other means, so the token value doesn't get used in our app.

**Comment by confact** [comment]
I get the javascript part to work but the cable-cr code insists on setting a token. Have anyone find out what to do here?

I would like to use the session in the cookie here or I have to do some monkey patching to generate JWT on the fly. My scenario also includes guests (no logins) using WebSocket as well, they should not need a JWT token.

BTW @jgaskins - I am trying to use your turbo - I will send a pr with some fixes later :)

**Comment by confact** [comment]
@fernandes rails have support for cookies and other things as well. Maybe let us get access to that and let us choose how we want to verify user?
```
    def find_verified_user
        if verified_user = User.find_by(id: cookies.encrypted[:user_id])
          verified_user
        else
          reject_unauthorized_connection
        end
    end
 ```

**Comment by fernandes** [comment]
hey guys, totally agree, let's make the token optional! 😄
