### ISSUE TITLE
Add overload for Channel.broadcast_to String, String

### ISSUE THREAD

**Issue by jwoertink** [cable-cr/cable#8]
Connection has a `broadcast_to` method that takes in 2 Strings

https://github.com/cable-cr/cable/blob/36103c088a7dc0791a329dd3b7c78b16f44be96a/src/cable/connection.cr#L139

But Channel only takes String, JSON::Any and String, Hash

https://github.com/cable-cr/cable/blob/36103c088a7dc0791a329dd3b7c78b16f44be96a/src/cable/channel.cr#L59-L64

What do you think about adding another one for String, String?

**Comment by fernandes** [comment]
connection has `(String, String)` because it sends the JSON as string.. cable works with the concept of JSON for messages - client and server side - I'm afraid that we add `(String, String)` on channel, someone pass a string like `"foo"` and then 💩 can happen 😊 

would we accept string and trust it will be always a serialized JSON or should we leave as `JSON::Any ` ?

**Comment by jwoertink** [comment]
Yeah, that makes sense. We can close this 👍

**Comment by confact** [comment]
@jwoertink @fernandes missed this issue, it is pretty close to #14 - Should we be worried about this scenario you are mentioning here @fernandes?

**Comment by fernandes** [comment]
@confact I'm not sure if we need, using overload we are handling correctly the string, and this is how Turbo works, so once we kept the test suite ✅ and added the new behavior we are good, maybe (probably) I was wrong on that message hahah
